added -ffpe-trap=list

diff --git a/ObjectOrientedSwirlCode/srcObj/Makefile b/ObjectOrientedSwirlCode/srcObj/Makefile
--- a/ObjectOrientedSwirlCode/srcObj/Makefile
+++ b/ObjectOrientedSwirlCode/srcObj/Makefile
@@ -20,13 +20,14 @@
 #   Ray Hixon update, using LAPACK3.8.0 routines
 #   March 8, 2018
 #   
-##   Jeff Severino
+##   Jeff Severino 
 ###################################################################
 F77      = gfortran
 F90      = gfortran
-F77FLAGS  = -c -O -fbounds-check -fcheck-array-temporaries -Wconversion -Wsurprising -Wall
-F90FLAGS  = -c -O -Ofast -std=f2008 -fbounds-check -fcheck-array-temporaries -Wconversion -Wsurprising -Wall
-# -Werror
+F77FLAGS  = -c -O -fbounds-check -fcheck-array-temporaries -Wconversion -Wsurprising -Wall -ffpe-trap=precision,underflow,overflow,invalid,zero
+F90FLAGS  = -c -O -std=f2008 -fbounds-check -fcheck-array-temporaries \
+			-Wconversion -Wsurprising -Wall -ffpe-trap=precision,underflow,overflow,invalid,zero
+#-Werror
 #F90FLAGS   = -c -g -C -qextchk -qflttrap -qhsflt -qxflag=dd24 \
 #	-v  -bloadmap:load.map
 FEXT     = f
@@ -142,27 +143,33 @@ LAPACK_OBJS =           \
          $(LAPACK_LOCATION)/zunmqr.o
 
 
-all:  $(OBJECTS)
-	@printf "%b" "$(COM_COLOR)$(COM_COLOR) $(OBJ_COLOR)$(@)$(NO_COLOR)\n" "Compiling $@\n";
-	@$(F90) -o $(EXE) $(BLAS_OBJS) \
-             $(LAPACK_OBJS) $(FITPACK_OBJS) $(OBJECTS) 2> $@.log; \
-	RESULT=$$?; \
-		if [ $$RESULT -ne 0 ]; then \
-			printf "%-60b%b" "$(COM_COLOR)$(COM_STRING)$(OBJ_COLOR) $@" "$(ERROR_COLOR)$(ERROR_STRING)$(NO_COLOR)\n"; \
-		elif [ -s $@.log ]; then \
-			printf "%-60b%b" "$(COM_COLOR)$(COM_STRING)$(OBJ_COLOR) $@" "$(WARN_COLOR)$(WARN_STRING)$(NO_COLOR)\n"; \
-		else  \
-			printf "%-60b%b" "$(COM_COLOR)$(COM_STRING)$(OBJ_COLOR) $(@F)" "$(OK_COLOR)$(OK_STRING)$(NO_COLOR)\n"; \
-		fi; \
-		cat $@.log; \
-        rm -f $@.log; \
-        exit $$RESULT
-
-	@mv $(EXE) $(EXECUTABLE_LOCATION);
-	@(cd $(EXECUTABLE_LOCATION); ./$(EXE));
-	@(cd $(EXECUTABLE_LOCATION); ./plotError.sh);
-
+#all:  $(OBJECTS)
+#	@printf "%b" "$(COM_COLOR)$(COM_COLOR) $(OBJ_COLOR)$(@)$(NO_COLOR)\n" "Compiling $@\n";
+#	@$(F90) -o $(EXE) $(BLAS_OBJS) \
+#             $(LAPACK_OBJS) $(FITPACK_OBJS) $(OBJECTS) 2> $@.log; \
+#	RESULT=$$?; \
+#		if [ $$RESULT -ne 0 ]; then \
+#			printf "%-60b%b" "$(COM_COLOR)$(COM_STRING)$(OBJ_COLOR) $@" "$(ERROR_COLOR)$(ERROR_STRING)$(NO_COLOR)\n"; \
+#		elif [ -s $@.log ]; then \
+#			printf "%-60b%b" "$(COM_COLOR)$(COM_STRING)$(OBJ_COLOR) $@" "$(WARN_COLOR)$(WARN_STRING)$(NO_COLOR)\n"; \
+#		else  \
+#			printf "%-60b%b" "$(COM_COLOR)$(COM_STRING)$(OBJ_COLOR) $(@F)" "$(OK_COLOR)$(OK_STRING)$(NO_COLOR)\n"; \
+#		fi; \
+#		cat $@.log; \
+#        rm -f $@.log; \
+#        exit $$RESULT
 #
+#	@mv $(EXE) $(EXECUTABLE_LOCATION);
+#	@(cd $(EXECUTABLE_LOCATION); ./$(EXE));
+#	@(cd $(EXECUTABLE_LOCATION); ./plotError.sh);
+#
+#
+all: $(OBJECTS)
+	$(F90) -o $(EXE) $(BLAS_OBJS) \
+        $(LAPACK_OBJS) $(FITPACK_OBJS) $(OBJECTS);\
+		mv $(EXE) $(EXECUTABLE_LOCATION); \
+		(cd $(EXECUTABLE_LOCATION); ./$(EXE)); \
+		(cd $(EXECUTABLE_LOCATION); ./plotError.sh);
 #  clean
 clean:
 	rm -f *.o *.c *.a *.mod
