Using ffpe flags

diff --git a/ObjectOrientedSwirlCode/srcObj/Makefile b/ObjectOrientedSwirlCode/srcObj/Makefile
--- a/ObjectOrientedSwirlCode/srcObj/Makefile
+++ b/ObjectOrientedSwirlCode/srcObj/Makefile
@@ -26,8 +26,7 @@ F77      = gfortran
 F90      = gfortran
 F77FLAGS  = -g -c -Og -fbounds-check -fcheck-array-temporaries -Wconversion -Wsurprising -Wall
 F90FLAGS  = -g -c -Og -std=f2008 -fbounds-check -fcheck-array-temporaries \
-			-Wconversion -Wsurprising -Wall
-#-ffpe-trap=denormal,overflow
+			-Wconversion -Wsurprising -Wall -ffpe-trap=denormal,overflow
 #-Werror
 #F90FLAGS   = -c -g -C -qextchk -qflttrap -qhsflt -qxflag=dd24 \
 #	-v  -bloadmap:load.map
@@ -144,32 +143,31 @@ LAPACK_OBJS =           \
          $(LAPACK_LOCATION)/zunmqr.o
 
 
-#all:  $(OBJECTS)
-#	@printf "%b" "$(COM_COLOR)$(COM_COLOR) $(OBJ_COLOR)$(@)$(NO_COLOR)\n" "Compiling $@\n";
-#	@$(F90) -o $(EXE) $(BLAS_OBJS) \
-#             $(LAPACK_OBJS) $(FITPACK_OBJS) $(OBJECTS) 2> $@.log; \
-#	RESULT=$$?; \
-#		if [ $$RESULT -ne 0 ]; then \
-#			printf "%-60b%b" "$(COM_COLOR)$(COM_STRING)$(OBJ_COLOR) $@" "$(ERROR_COLOR)$(ERROR_STRING)$(NO_COLOR)\n"; \
-#		elif [ -s $@.log ]; then \
-#			printf "%-60b%b" "$(COM_COLOR)$(COM_STRING)$(OBJ_COLOR) $@" "$(WARN_COLOR)$(WARN_STRING)$(NO_COLOR)\n"; \
-#		else  \
-#			printf "%-60b%b" "$(COM_COLOR)$(COM_STRING)$(OBJ_COLOR) $(@F)" "$(OK_COLOR)$(OK_STRING)$(NO_COLOR)\n"; \
-#		fi; \
-#		cat $@.log; \
-#        rm -f $@.log; \
-#        exit $$RESULT
+all:  $(OBJECTS)
+	@printf "%b" "$(COM_COLOR)$(COM_COLOR) $(OBJ_COLOR)$(@)$(NO_COLOR)\n" "Compiling $@\n";
+	@$(F90) -o $(EXE) $(BLAS_OBJS) \
+             $(LAPACK_OBJS) $(FITPACK_OBJS) $(OBJECTS) 2> $@.log; \
+	RESULT=$$?; \
+		if [ $$RESULT -ne 0 ]; then \
+			printf "%-60b%b" "$(COM_COLOR)$(COM_STRING)$(OBJ_COLOR) $@" "$(ERROR_COLOR)$(ERROR_STRING)$(NO_COLOR)\n"; \
+		elif [ -s $@.log ]; then \
+			printf "%-60b%b" "$(COM_COLOR)$(COM_STRING)$(OBJ_COLOR) $@" "$(WARN_COLOR)$(WARN_STRING)$(NO_COLOR)\n"; \
+		else  \
+			printf "%-60b%b" "$(COM_COLOR)$(COM_STRING)$(OBJ_COLOR) $(@F)" "$(OK_COLOR)$(OK_STRING)$(NO_COLOR)\n"; \
+		fi; \
+		cat $@.log; \
+        rm -f $@.log; \
+        exit $$RESULT
+
+	@mv $(EXE) $(EXECUTABLE_LOCATION);
+	@(cd $(EXECUTABLE_LOCATION); ./$(EXE));
 #
-#	@mv $(EXE) $(EXECUTABLE_LOCATION);
-#	@(cd $(EXECUTABLE_LOCATION); ./$(EXE));
-#	@(cd $(EXECUTABLE_LOCATION); ./plotError.sh);
 #
-#
-all: $(OBJECTS)
-	$(F90) -o $(EXE) $(BLAS_OBJS) \
-        $(LAPACK_OBJS) $(FITPACK_OBJS) $(OBJECTS);\
-		mv $(EXE) $(EXECUTABLE_LOCATION); \
-		(cd $(EXECUTABLE_LOCATION); ./$(EXE))#; \		(cd $(EXECUTABLE_LOCATION); ./plotError.sh);
+#all: $(OBJECTS)
+#	$(F90) -o $(EXE) $(BLAS_OBJS) \
+#        $(LAPACK_OBJS) $(FITPACK_OBJS) $(OBJECTS);\
+#		mv $(EXE) $(EXECUTABLE_LOCATION); \
+#		(cd $(EXECUTABLE_LOCATION); ./$(EXE))#; \		(cd $(EXECUTABLE_LOCATION); ./plotError.sh);
 #  clean
 clean:
 	rm -f *.o *.c *.a *.mod
